#!bin/bash

GENERATOR=GENIE
#TUNE=G18_10a_00_000
TUNE=G18_10s_00_000
#TUNE=G18_10a_02_11a
#TUNE=G21_11a_00_000
PARTICLE=14
TARGET=1000180400
CHANNEL=CCMEC
#NUMEVENTS=500000
NUMEVENTS=100000 # Caveat: This is not automatic in compute_var_GENIE.C, need to set the NUMEVENTS in loop there
GENIE_FILES_DIR=$PWD/gen_files
GENIE_REWEIGHT_FILES_DIR=$PWD/genie_reweight_files
MINTWEAK=0
MINTWEAK2=1
MAXTWEAK=1
MAXTWEAK2=1
NUMTWKDIALVAL=2
SYSTEMATICNAME=NormCCMEC
#SYSTEMATICNAME=DecayAngMEC
#SYSTEMATICNAME2=DecayAng2MEC
#SYSTEMATICNAME=FracPN_CCMEC
#SYSTEMATICNAME=FracDelta_CCMEC
#SYSTEMATICNAME=XSecShape_CCMEC
#SYSTEMATICNAME=EnergyDependence_CCMEC

SEED=26874    #GENIE_G18_10s_00_000_14_1000180400_CCMEC_26874.ghep.root
#SEED=31038    #GENIE_G18_10a_00_000_14_1000180400_CCMEC_31038.ghep.root

GHEPFILENAME=${GENERATOR}_${TUNE}_${PARTICLE}_${TARGET}_${CHANNEL}_${SEED}.ghep.root

root -l -q "compute_var_GENIE.C(\"${GENIE_FILES_DIR}/${GENERATOR}_${TUNE}_${PARTICLE}_${TARGET}_${CHANNEL}_${SEED}.gst.root\",\"${GENERATOR}_${TUNE}_${PARTICLE}_${TARGET}_${CHANNEL}_${SEED}_${NUMEVENTS}\")"

#cp var_files/var_out_${GENERATOR}_${TUNE}_${PARTICLE}_${TARGET}_${CHANNEL}_${SEED}_${NUMEVENTS}_copy.root var_files/var_out_${GENERATOR}_${TUNE}_${PARTICLE}_${TARGET}_${CHANNEL}_${SEED}_${NUMEVENTS}.root

root -l -q "copy_weights_branch.cpp(\"var_files/var_out_${GENERATOR}_${TUNE}_${PARTICLE}_${TARGET}_${CHANNEL}_${SEED}_${NUMEVENTS}.root\", \"${GENIE_REWEIGHT_FILES_DIR}/${GENERATOR}_${TUNE}_${PARTICLE}_${TARGET}_${CHANNEL}_${SEED}_${SYSTEMATICNAME}_dial_from_${MINTWEAK}_to_${MAXTWEAK}_${NUMEVENTS}.grwght.root\", \"${SYSTEMATICNAME}\")"

root -l make_plots.C
